import postgres from "postgres";
const sql = postgres(process.env.DATABASE_URL, { max: 1, ssl: "require", prepare: false, connect_timeout: 60 });
const iso = (d) => (d?.toISOString ? d.toISOString().slice(5, 16).replace("T", " ") : d);
const [s] = await sql`select max(completed_at) filter (where status='completed') as last_ok, count(*) filter (where completed_at >= now() - interval '24 hours' and status='failed')::int as fails24 from sync_logs where job_name='ads-autosync'`;
console.log(`1. ads-autosync: último OK ${iso(s.last_ok)} | fails 24h: ${s.fails24}`);
const [o] = await sql`select max(synced_at) as last, count(*) filter (where created_time < '2000-01-01')::int as garbage from organic_posts`;
console.log(`2. orgánico: último sync ${iso(o.last)} | garbage-1970: ${o.garbage}`);
const runs = await sql`select r.status, count(*)::int as n from heartbeat_runs r where r.created_at >= now() - interval '24 hours' group by r.status order by n desc`;
console.log("3. runs flota 24h:", runs.map((r) => `${r.status}=${r.n}`).join(", "));
const [ai] = await sql`select status from issues where id = '26a80937-0dda-42c5-a2df-9515137717c4'`;
console.log(`4. issue auditoría de perfil: ${ai.status}`);
const ad = await sql`select adapter_type, count(*)::int as n from agents group by adapter_type`;
console.log("5. flota:", ad.map((r) => `${r.adapter_type}=${r.n}`).join(", "));
const fb = await sql`select count(*)::int as n, max(updated_at) as last from client_memory where key = 'super-redes-feedback'`;
console.log(`6. feedback Super Redes: ${fb[0].n} clientes, última ${iso(fb[0].last)}`);
const [w] = await sql`select count(*)::int as n from agent_wakeup_requests`;
console.log(`7. wakeups: ${w.n} filas`);
const [ic] = await sql`select count(*)::int as n from issues where created_at >= now() - interval '48 hours'`;
console.log(`8. issues nuevos 48h: ${ic.n}`);
await sql.end();
